# Pass --build-upon-default-config to detekt to inherit default values
config:
  validation: true
  # when writing own rules with new properties, exclude the property path e.g.: "my_rule_set,.*>.*>[my_property]"

complexity:
  TooManyFunctions:
    active: false

style:
  ReturnCount:
    active: true
    max: 3
    excludedFunctions: "equals,onOptionsItemSelected,onPreferenceTreeClick,onMenuItemSelected"
  MaxLineLength:
    active: false
  SpacingBetweenPackageAndImports:
    active: true

exceptions:
  TooGenericExceptionCaught:
    active: false
  PrintStackTrace:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true
    active: true

formatting:
  # this is the ktlint variation of MaxLineLength
  # it works only at file level so we turn it off
  MaximumLineLength:
    active: false
  NoWildcardImports:
    active: false
  # This rules overlaps with style>NewLineAtEndOfFile so is turned off
  FinalNewline:
    active: false
